#ifndef GPIBGENERALDEVICE_GLOBAL_H
#define GPIBGENERALDEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPIBGENERALDEVICE_LIBRARY)
#  define GPIBGENERALDEVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GPIBGENERALDEVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GPIBGENERALDEVICE_GLOBAL_H
