#ifndef ISEFILEFORMAT_GLOBAL_H
#define ISEFILEFORMAT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ISEFILEFORMAT_LIBRARY)
#  define ISEFILEFORMATSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ISEFILEFORMATSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ISEFILEFORMAT_GLOBAL_H
